const ActionMovies = [
    {
        id:"1",
        name:"Guntur Kaaram",
        image:"https://telugu.filmibeat.com/img/2024/01/guntur-kaaram-mahesh-babu-446-1706320131.jpg",
        headimage:"https://cdn.gulte.com/wp-content/uploads/2023/08/m-969.jpg",
        censor:"U/A",
        duration:"2h 39m",
        year:"2024",
        overview: "Years after his mother abandons him and remarries, a man demands answers when he's asked to sign a document denying he is her son as she runs for office.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"2",
        name:"HanuMan",
        image:"https://img.etimg.com/thumb/width-1600,height-900,imgsize-112166,resizemode-75,msid-106749597/news/new-updates/director-prasanth-varmas-hanuman-a-culturally-rooted-indian-superhero-film-hits-cinemas-today.jpg",
        headimage:"https://content.tupaki.com/en/feeds/2024/01/14/253014-ovevwka5.gif",
        censor:"U",
        duration:"2h 38m",
        year:"2024",
        overview: "An imaginary place called Anjanadri where the protagonist gets the powers of Hanuman and fights for Anjanadri.",
        Mem1Img:"https://www.filmiforest.com/img/profile_image/teja-sajja1.jpg",
        Mem1Name:"Teja Sajja",
        Mem2Img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Amritha_Aiyer_at_HanuMan_gratitude_meet_%281%29.jpg/640px-Amritha_Aiyer_at_HanuMan_gratitude_meet_%281%29.jpg",
        Mem2Name:"Amritha Aiyer",
        Mem3Img:"https://i.pinimg.com/736x/05/fb/e2/05fbe224dda37f87c8e73e10e19debfe.jpg",
        Mem3Name:"Varalaxmi",
        Mem4Img:"https://m.media-amazon.com/images/M/MV5BNTk1MWQ3ZmQtMzEzYi00NmMwLThjZjctZjcxYTQ2ZjZhOTg1XkEyXkFqcGdeQXVyMzYxOTQ3MDg@._V1_.jpg",
        Mem4Name:"Vinay Rai",
        Mem5Img:"https://m.media-amazon.com/images/M/MV5BMzdjNzY0NjUtYjNiNS00ODMwLTk4MzctMzkzM2Q5MDZmYmEyXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
        Mem5Name:"Ravi Teja",
        Mem6Img:"https://upload.wikimedia.org/wikipedia/commons/d/dc/Samuthirakani_at_Sandamarudham_Audio_Launch.jpg",
        Mem6Name:"Samuthirakani",
        Mem7Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyZWFKVehMFGU9-GnPs5d95SPvjOVjM62wNg&s",
        Mem7Name:"Vennela Kishore",
        Crew1Img:"https://cdn.gulte.com/wp-content/uploads/2023/05/Unknown-1.jpeg",
        Crew1Name:"prasanth varma",
        Crew2Img:"https://images.filmibeat.com/img/popcorn/profile_photos/hari-gaura-20190522105333-34491.jpg",
        Crew2Name:"Hari Gaura",
        Crew3Img:"https://images.filmibeat.com/img/popcorn/profile_photos/k-niranjan-reddy-20240111184645-61321.jpg",
        Crew3Name:"K Niranjan Reddy",
    },
    {
        id:"3",
        name:"Captian Miller",
        image:"https://indiaglitz-media.s3.amazonaws.com/telugu/home/captain-miller-review-1.jpg",
        headimage:"https://static.toiimg.com/thumb/msid-106417238,width-1280,height-720,resizemode-4/106417238.jpg",
        censor:"U/A",
        duration:"2h 37m",
        year:"2024",
        overview: "A man leaves and turns against the British-led Indian military after witnessing atrocity.",
        Mem1Img:"https://upload.wikimedia.org/wikipedia/commons/8/86/Dhanush_at_the_%E2%80%98Asuran%E2%80%99_Success_Meet.jpg",
        Mem1Name:"Dhanush",
        Mem2Img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Priyanka_Arul_Mohan_at_Etharkkum_Thunindhavan_pre_release_event_%28cropped%29.jpg/170px-Priyanka_Arul_Mohan_at_Etharkkum_Thunindhavan_pre_release_event_%28cropped%29.jpg",
        Mem2Name:"Priyanka Mohan",
        Mem3Img:"https://i.pinimg.com/474x/86/7f/9d/867f9d26b2477e996ea8a873c20ee9e8.jpg",
        Mem3Name:"Sundeep Kishan",
        Mem4Img:"https://www.behindwoods.com/tamil-actress/nivedhithaa-sathish/nivedhithaa-sathish-stills-photos-pictures-152.jpg",
        Mem4Name:"Nivedhithaa",
        Mem5Img:"https://m.media-amazon.com/images/M/MV5BMDM2ZTE0MzgtOGY0Ny00YjljLWE3MzYtOTUzZDc2NDYyY2EzXkEyXkFqcGdeQXVyNzY3MTExNTA@._V1_.jpg",
        Mem5Name:"Shiva Rajkumar",
        Mem6Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvVV7xUZTBFuVROB1VhAiyjaqpSu5g-u_yCg&s",
        Mem6Name:"Sonnenblick",
        Crew1Img:"https://th-i.thgim.com/public/entertainment/movies/bz2x35/article67722835.ece/alternates/FREE_1200/DSC_5411.JPG",
        Crew1Name:"Arun matheswaran",
        Crew2Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBAx7Bus2boSNtuZ_3gdgjKbvgjLkaH37FoA&s",
        Crew2Name:"G V Prakash Kumar",
        Crew3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSveHaisMaW7IYdkTmQWcPsNJDkpl2dmKGfgw&s",
        Crew3Name:"Sendhil Thyagarajan",
    },
    {
        id:"4",
        name:"Bhimaa",
        image:"https://telugu.filmibeat.com/img/2024/03/bhimaa-gopichand-821-1709791988.jpg",
        headimage:"https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/3342/1712985613342-i",
        censor:"U/A",
        duration:"2h 21m",
        year:"2024",
        overview: "Mysterious incidents at a historical temple bring a detective to a small town to investigate. He seeks the truth behind the strange happenings.",
        Mem1Img:"https://m.media-amazon.com/images/M/MV5BNGIwZDVkYWEtZmY5Mi00M2ViLTg4MTQtZTlkMzk1NGJmYjI4XkEyXkFqcGdeQXVyNjkwOTg4MTA@._V1_.jpg",
        Mem1Name:"Gopichand",
        Mem2Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeTpGZyb-L47UvqSHFMQjWN8auLQtzVHNfyw&s",
        Mem2Name:"Malvika",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCifrein-gXIU3OTs2186lSsSC9dAe6M0K9g&s",
        Mem3Name:"Priya Bhavani",
        Mem4Img:"https://upload.wikimedia.org/wikipedia/commons/c/c8/Nassar_at_Oru_Kadhai_Sollattumaa_Audio_Launch.jpg",
        Mem4Name:"Nassar",
        Mem5Img:"https://www.filmibeat.com/img/popcorn/profile_photos/mukesh-tiwari-hin-20151106120619-938.jpg",
        Mem5Name:"Mukesh Tiwari",
        Mem6Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyZWFKVehMFGU9-GnPs5d95SPvjOVjM62wNg&s",
        Mem6Name:"Vennela Kishore",
        Mem7Img:"https://m.media-amazon.com/images/M/MV5BMjFlNDJmYWItNmQyNy00ZTdkLThjYmEtNzYxYjMyYTgzOGQyXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem7Name:"Shamna Kasim",
        Crew1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAWuXubJAwIlbTS1i1neeZhSWwONla-JXphA&s",
        Crew1Name:"Harsha A",
        Crew2Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ravi-basrur-20190801143614-32598.jpg",
        Crew2Name:"Ravi Basrur",
        Crew3Img:"https://images.filmibeat.com/img/popcorn/profile_photos/kk-radha-mohan-20200929092829-9882.jpg",
        Crew3Name:"K K Radhamohan",
    },
    {
        id:"5",
        name:"KrishnaAmma",
        image:"https://m.media-amazon.com/images/S/pv-target-images/0f296dd2e83f76c0b0c0b5142df888ffe84780102fbde68df95abbb072bd41ba.jpg",
        headimage:"https://www.teluguglobal.com/h-upload/2024/04/27/1322600-krishnamma-1.webp",
        censor:"U",
        duration:"2h 18m",
        year:"2024",
        overview: "Three orphans form an unbreakable bond, growing up together on the Krishna River's banks in Vijayawada, India, and become each other's family.",
        Mem1Img:"https://upload.wikimedia.org/wikipedia/commons/f/f8/Satyadev-Mana-oori-ramayanam-audio-launch.jpg",
        Mem1Name:"Satyadev",
        Mem2Img:"https://images.filmibeat.com/img/popcorn/profile_photos/athira-raj-20230620142329-57559.jpg",
        Mem2Name:"Athira Raj",
        Mem3Img:"https://content.tupaki.com/twdata/2021/0121/photos/actress/Archana%20Shastry%20Interview%20Photos/normal/Archana%20Shastry%20Interview%20Photos_7.jpg",
        Mem3Name:"Archana",
        Mem4Img:"https://m.media-amazon.com/images/M/MV5BYjhkYTAxOWUtOWFmMi00ZjViLTliY2EtMzA2MWVjMTgwOTg1XkEyXkFqcGdeQXVyNjk1MjYyNTA@._V1_.jpg",
        Mem4Name:"Archana Iyer",
        Mem5Img:"https://static.toiimg.com/thumb/74281304.cms?width=170&height=240",
        Mem5Name:"Raghu Kunche",
        Mem6Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlu-HWt2pasaakMl1fGotz41UoUlSB_KNjcQ&s",
        Mem6Name:"Satyam Rajesh",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/lakshman-20240313162342-34629.jpg",
        Mem7Name:"Laxman Meesala",
        Crew1Img:"https://in.bmscdn.com/artist/vv-gopala-krishna-2020253-1714041666.jpg",
        Crew1Name:"V V Gopala Krishna",
        Crew2Img:"https://i.scdn.co/image/ab6761610000e5ebc1287c819b75d64bcc355338",
        Crew2Name:"Kaala Bhairava",
        Crew3Img:"https://in.bmscdn.com/artist/krishna-kommalapati-2020254-1714041793.jpg",
        Crew3Name:"Krishna Kommalapati",
    },
    {
        id:"6",
        name:"Operation Valentine",
        image:"https://images.deccanherald.com/deccanherald/2023-12/40d485f5-a28d-488a-805d-1df01a104989/Operation_Valentine.jpg?w=1200&h=675&auto=format%2Ccompress&fit=max&enlarge=true",
        headimage:"https://www.koimoi.com/wp-content/new-galleries/2024/03/operation-valentine-at-the-worldwide-box-office-closing-collection-001.jpg",
        censor:"U/A",
        duration:"2h 13m",
        year:"2024",
        overview: "Showcasing the indomitable spirits of the Indian Air Force heroes on the frontlines and the challenges they face during one of the biggest, fiercest aerial attacks that India has ever seen.",
        Mem1Img:"https://m.media-amazon.com/images/M/MV5BMTQ2MzZhYWItYjdiYS00NmYyLThmNjYtMDNmMzRiYWZmMGU1XkEyXkFqcGdeQXVyNDc2NzU1MTA@._V1_.jpg",
        Mem1Name:"Varun Tej",
        Mem2Img:"https://upload.wikimedia.org/wikipedia/commons/c/ca/Manushi_Chhillar_attends_a_press_meet_for_the_Gem_and_Jewellery_Export_Promotion_Council_of_India_%28GJEPC%29_in_2023_%28cropped%29.jpg",
        Mem2Name:"Manushi",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2yo-1DCPKuLPuLSVfhbGgU5W6ZaprCrdjvg&s",
        Mem3Name:"Ruhani",
        Mem4Img:"https://m.media-amazon.com/images/M/MV5BMjkzOGQ5NjEtZGMzZi00NDEwLWI1ZTUtOTIzZTE2YTZhMDMyXkEyXkFqcGdeQXVyMTY0MDc4NDE4._V1_FMjpg_UX1000_.jpg",
        Mem4Name:"Shataf Figar",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/paresh-pahuja-20221110102735-40982.jpg",
        Mem5Name:"Paresh",
        Mem6Img:"https://upload.wikimedia.org/wikipedia/commons/5/5f/Abhinav_%28cropped%29.jpg",
        Mem6Name:"Abhinav",
        Mem7Img:"https://m.media-amazon.com/images/M/MV5BNDRmNjc4OTktYmZhNC00NThkLWExYTItOTYyYWYzZTM1MjhhXkEyXkFqcGc@._V1_.jpg",
        Mem7Name:"Anish Kuruvilla",
        Crew1Img:"https://pbs.twimg.com/profile_images/1571460934333505538/5z33jyZj_400x400.jpg",
        Crew1Name:"shakti pratap",
        Crew2Img:"https://i.scdn.co/image/ab6761610000e5eb86d311f84a0fbaaedeefd640",
        Crew2Name:"Mickey J Meyer",
        Crew3Img:"https://www.filmibeat.com/img/popcorn/profile_photos/sidhu-mudda-tel-20220407133313-7390.jpg",
        Crew3Name:"Sandeep Mudda",
    },
    {
        id:"7",
        name:"Indian 2",
        image:"https://static.tnn.in/thumb/msid-111663850,thumbsize-88560,width-1280,height-720,resizemode-75/111663850.jpg?quality=100",
        headimage:"https://i.cdn.newsbytesapp.com/images/30135351713078638.jpeg",
        censor:"U/A",
        duration:"3h",
        year:"2024",
        overview: "Senapathy, an ex-freedom fighter turned vigilante who fights against corruption. Senapathy returns to the country to aid a young man who has been exposing corrupt politicians in the country through videos on the internet.",
        Mem1Img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Kamal_haasan.jpg/220px-Kamal_haasan.jpg",
        Mem1Name:"Kamal Haasan",
        Mem2Img:"https://images.filmibeat.com/img/popcorn/profile_photos/vivek-20191128144347-2946.jpg",
        Mem2Name:"Vivek ",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCifrein-gXIU3OTs2186lSsSC9dAe6M0K9g&s",
        Mem3Name:"Priya Bhavani ",
        Mem4Img:"https://upload.wikimedia.org/wikipedia/commons/7/78/Rakul-Preet-snapped-at-the-Jio-Studios-Infinite-Together-event_%28cropped%29.jpg",
        Mem4Name:"Rakul Preet ",
        Mem5Img:"https://m.media-amazon.com/images/M/MV5BMTUxNDgxMzYzNl5BMl5BanBnXkFtZTgwNTk0MzQ0MDI@._V1_FMjpg_UX1000_.jpg",
        Mem5Name:"Siddharth",
        Mem6Img:"https://upload.wikimedia.org/wikipedia/commons/4/40/SJ_Surya_at_Iraivi_Press_Meet.jpg",
        Mem6Name:"SJ Surya",
        Mem7Img:"https://thebiodiary.com/uploads/bio/barahamanad-1.jpg",
        Mem7Name:"Brahmanandam",
        Crew1Img:"https://m.media-amazon.com/images/M/MV5BMjljNmM2ZmUtMTVlYS00YzY1LTgzNGUtMDY3OGMxMmNmNzY5XkEyXkFqcGdeQXVyMjYwMDk5NjE@._V1_.jpg",
        Crew1Name:"Shankar",
        Crew2Img:"https://images.filmibeat.com/img/popcorn/profile_photos/anirudh-ravichander-20221117133315-26845.jpg",
        Crew2Name:"Anirudh Ravichander",
        Crew3Img:"https://upload.wikimedia.org/wikipedia/commons/d/d4/Subaskaran-Allirajah-Profile.jpg",
        Crew3Name:"Subaskaran",
    },
    {
        id:"8",
        name:"Maharaja",
        image:"https://staticimg.amarujala.com/assets/images/2023/09/11/maharaja-maharaja-poster-maharaja-first-look-maharaja-first-look-poster-vijay-sethupathi-vijay_1694372591.jpeg",
        headimage:"https://assets.telegraphindia.com/telegraph/2024/Jun/1717580397_maharaja.jpg",
        censor:"U/A",
        duration:"2h 30m",
        year:"2024",
        overview: "A barber seeks vengeance after his home is burglarized, cryptically telling police his lakshmi has been taken, leaving them uncertain if it's a person or object. His quest to recover the elusive lakshmi unfolds.",
        Mem1Img:"https://upload.wikimedia.org/wikipedia/commons/5/51/MAKKAL_SELVAN_Vijay_Sethupathi.png",
        Mem1Name:"Vijay Sethupathi",
        Mem2Img:"https://upload.wikimedia.org/wikipedia/commons/5/57/Anurag_Kashyap_02.jpg",
        Mem2Name:"Anurag Kashyap",
        Mem3Img:"https://upload.wikimedia.org/wikipedia/commons/b/be/Mamta_Mohandas_Red_FM_2020.jpg",
        Mem3Name:"Mamta Mohandas",
        Mem4Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHJ5PvFxK45eorCfrPOt8YnoFaRZodZIPk5Q&s",
        Mem4Name:"Divya Bharathi",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/sachananamidass-20240618093349-63681.jpg",
        Mem5Name:"Sachana Namidass",
        Mem6Img:"https://images.filmibeat.com/img/popcorn/profile_photos/natarajan-subramaniam-20180326111132-3574.jpg",
        Mem6Name:"Natarajan Subramaniam",
        Mem7Img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Actress_Lizzie_Antony.jpg/220px-Actress_Lizzie_Antony.jpg",
        Mem7Name:"Lizzie Antony",
        Crew1Img:"https://images.filmibeat.com/img/popcorn/profile_photos/nithilan-swaminathan-20230713122819-37021.jpg",
        Crew1Name:"nithilan swaminathan",
        Crew2Img:"https://in.bmscdn.com/iedb/artist/images/website/poster/large/b-ajaneesh-loknath-1044651-1681029949.jpg",
        Crew2Name:"Ajaneesh Loknath",
        Crew3Img:"https://d14u0p1qkech25.cloudfront.net/1452733140_0ffc6aa2-a967-4baa-ae91-28c086b9f5eb_thumbnail_250x250",
        Crew3Name:"Jagadish Palanisamy",
    },
    {
        id:"9",
        name:"Siren",
        image:"https://images.ottplay.com/images/siren-poster-1707358805.jpg?impolicy=ottplay-20210210&width=1200&height=675&format=webp&quality=50",
        headimage:"https://images.indianexpress.com/2024/02/Jayam-Ravi-in-Siren.jpg",
        censor:"U/A",
        duration:"2h 34m",
        year:"2024",
        overview: "An ambulance driver turned criminal eagerly awaits his release from prison, but it takes 14 years.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"10",
        name:"Leo",
        image:"https://static.toiimg.com/thumb/msid-101172246,width-1280,height-720,resizemode-4/101172246.jpg",
        headimage:"https://static.toiimg.com/thumb/msid-101275525,width-1280,height-720,resizemode-4/101275525.jpg",
        censor:"U/A",
        duration:"2h 44m",
        year:"2023",
        overview:"Parthiban is a mild-mannered cafe owner in Kashmir, who fends off a gang of murderous thugs and gains attention from a drug cartel claiming he was once a part of them.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"11",
        name:"Jailer",
        image:"https://img.indiaforums.com/article/1280x720/19/9227-the-rajinikanth-fever-offices-down-south-announce-holiday-on-10th-owing-to-jailers-release.jpg",
        headimage:"https://www.hindustantimes.com/ht-img/img/2023/08/10/1600x900/rajinikanth_jailer_1691643831744_1691643831920.jpeg",
        censor:"U/A",
        duration:"2h 48m",
        year:"2023",
        overview: "A retired jailer goes on a manhunt to find his son's killers. But the road leads him to a familiar, albeit a bit darker place. Can he emerge from this complex situation successfully?",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"12",
        name:"Salaar: Cease Fire - part 1",
        image:"https://static.toiimg.com/thumb/msid-103364335,width-1280,height-720,resizemode-4/103364335.jpg",
        headimage:"https://www.koimoi.com/wp-content/new-galleries/2024/05/get-ready-for-an-action-packed-adventure-with-the-world-television-premiere-of-hombale-films-salaar-part-1-ceasefire-on-star-gold-001.jpg",
        censor:"U/A",
        duration:"2h 55m",
        year:"2024",
        overview: "The fate of a violently contested kingdom hangs on the fraught bond between two friends-turned-foes in this saga of power, bloodshed and betrayal.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"13",
        name:"Jawan",
        image:"https://akm-img-a-in.tosshub.com/indiatoday/images/media_bank/202309/shah-rukh-khan--jawan--srk-films-295651-16x9.jpg?VersionId=Ddej.9DLpQW91sSb7YB6E_5yd7e1xypP",
        headimage:"https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/07/jawan-1.jpg",
        censor:"U/A",
        duration:"2h 49m",
        year:"2023",
        overview: "A prison warden recruits inmates to commit outrageous crimes that shed light on corruption and injustice - and that lead him to an unexpected reunion.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"14",
        name:"KGF chapter 1",
        image:"https://wallpapers.com/images/hd/kgf-chapter-1-two-sides-of-rocky-t3e8k8stejnl6qka.jpg",
        headimage:"https://images.ottplay.com/images/KGF:_Chapter_1_2018_movie_tmdb_backdrop_1.jpg?impolicy=ottplay-20210210&width=1200&height=675&format=webp&quality=50",
        censor:"U/A",
        duration:"2h 35m",
        year:"2018",
        overview: "In the 1970s, a gangster named Rocky goes undercover as a slave to assassinate the owner of a notorious gold mine known as the Kolar Gold Fields.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },
    {
        id:"15",
        name:"KGF chapter 2",
        image:"https://m.media-amazon.com/images/M/MV5BNWM3MTAxODgtZWViMC00ODVkLTkzM2UtZjNjNmI0MDFmOTc3XkEyXkFqcGdeQXVyMTQ3Mzk2MDg4._V1_.jpg",
        headimage:"https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2022/04/pjimage-81-1649901154.jpg",
        censor:"U/A",
        duration:"2h 46m",
        year:"2021",
        overview: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes, while the government sees him as a threat to law and order. Rocky must battle threats from all sides for unchallenged supremacy.",
        Mem1Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKGLmHlBFdCXIqIG0W8Y9gV1fjGffe51ruNw&s",
        Mem1Name:"Mahesh Babu",
        Mem2Img:"https://m.media-amazon.com/images/M/MV5BNDM0NDkwNzItNGVlNi00ZjM4LThkM2EtOTg3ZDgyNGMwZDJjXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg",
        Mem2Name:"Sree Leela",
        Mem3Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4oWJdFgTqN_PpjQ2oluXbcsjGboiXC2pPQ&s",
        Mem3Name:"Meenakshi",
        Mem4Img:"https://images.filmibeat.com/img/popcorn/profile_photos/ramya-krishnan-20180731102950-4865.jpg",
        Mem4Name:"Ramya Krishnan",
        Mem5Img:"https://images.filmibeat.com/img/popcorn/profile_photos/prakash-raj-20230718123643-152.jpg",
        Mem5Name:"Prakash Raj",
        Mem6Img:"https://m.media-amazon.com/images/M/MV5BZTA1M2U3NmYtYjgyZC00MzBjLTk0MmMtNDdlOTE0Y2ZiNzQ0XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_FMjpg_UX1000_.jpg",
        Mem6Name:"Jagapathi Babu",
        Mem7Img:"https://images.filmibeat.com/img/popcorn/profile_photos/jayaram-20230103142507-2834.jpg",
        Mem7Name:"Jayaram",
        Crew1Img:"https://img.studioflicks.com/wp-content/uploads/2021/09/27110330/Trivikram-Srinivas.jpg",
        Crew1Name:"Trivikram",
        Crew2Img:"https://upload.wikimedia.org/wikipedia/commons/e/e8/S._Thaman_at_Damaal_Dumeel_Audio_Launch.jpg",
        Crew2Name:"Thaman S",
        Crew3Img:"https://filmyfocus.com/wp-content/uploads/2023/06/Radha-Krishna.png",
        Crew3Name:"Radha Krishna",
    },

]

export default ActionMovies;